server:
  port: 10002

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinten10/Aditum-Config/
          search-paths: respo
          username:
          passphrase:
      label: master
