server:
  port: 10001

eureka:
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/